WardrobeMVC/Models/OutfitName.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutfitName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutfitName()
        {
            this.OutfitParts = new HashSet<OutfitPart>();
        }
    
        public int OutfitID { get; set; }
        public string Name { get; set; }
        public string Season { get; set; }
        public string Occasion { get; set; }
        public int CharchterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitPart> OutfitParts { get; set; }
        public virtual Charachter Charachter { get; set; }
    }
}

WardrobeMVC/Controllers/OutfitNamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeMVC.Models;

namespace WardrobeMVC.Controllers
{
    public class OutfitNamesController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: OutfitNames
        public ActionResult Index()
        {
            var outfitNames = db.OutfitNames.Include(o => o.Charachter);
            return View(outfitNames.ToList());
        }

        // GET: OutfitNames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitName outfitName = db.OutfitNames.Find(id);
            FullOutfit fullOutfit = new FullOutfit();
            fullOutfit.OutfitParts = (from c in db.OutfitParts where c.OutfitID==(id) select c).ToList();
            fullOutfit.Sheos = (from c in db.OutfitParts where c.OutfitID==(id) select c.Shoe).ToList();
            fullOutfit.Tops = (from c in db.OutfitParts where c.OutfitID==(id) select c.Top).ToList();
            fullOutfit.Accessories = (from c in db.OutfitParts where c.OutfitID==(id) select c.Accessory).ToList();
            fullOutfit.Bottoms = (from c in db.OutfitParts where c.OutfitID==(id) select c.Bottom).ToList();
            fullOutfit.Name = outfitName.Name;
            fullOutfit.Occasion = outfitName.Occasion;
            fullOutfit.Season = outfitName.Season;
            fullOutfit.Actor = outfitName.Charachter.Photo;
            //foreach (OutfitPart p in fullOutfit.OutfitParts)
            //{
            //    fullOutfit.Tops.Add((from c in db.Tops where c.OutfitParts.Equals(p) select c));
            //}
            if (outfitName == null)
            {
                return HttpNotFound();
            }
            return View(fullOutfit);
        }

        // GET: OutfitNames/Create
        public ActionResult Create()
        {
            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName");
            return View();
        }

        // POST: OutfitNames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OutfitID,Name,Season,Occasion,CharchterID")] OutfitName outfitName)
        {
            if (ModelState.IsValid)
            {
                db.OutfitNames.Add(outfitName);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName", outfitName.CharchterID);
            return View(outfitName);
        }

        // GET: OutfitNames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitName outfitName = db.OutfitNames.Find(id);
            if (outfitName == null)
            {
                return HttpNotFound();
            }
            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName", outfitName.CharchterID);
            return View(outfitName);
        }

        // POST: OutfitNames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OutfitID,Name,Season,Occasion,CharchterID")] OutfitName outfitName)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outfitName).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName", outfitName.CharchterID);
            return View(outfitName);
        }

        // GET: OutfitNames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitName outfitName = db.OutfitNames.Find(id);
            if (outfitName == null)
            {
                return HttpNotFound();
            }
            return View(outfitName);
        }

        // POST: OutfitNames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OutfitName outfitName = db.OutfitNames.Find(id);
            db.OutfitNames.Remove(outfitName);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeMVC/Controllers/OutfitPartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeMVC.Models;

namespace WardrobeMVC.Controllers
{
    public class OutfitPartsController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: OutfitParts
        public ActionResult Index()
        {
            var outfitParts = db.OutfitParts.Include(o => o.Accessory).Include(o => o.Bottom).Include(o => o.OutfitName).Include(o => o.Shoe).Include(o => o.Top);
            return View(outfitParts.ToList());
        }

        // GET: OutfitParts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitPart outfitPart = db.OutfitParts.Find(id);
            if (outfitPart == null)
            {
                return HttpNotFound();
            }
            return View(outfitPart);
        }

        // GET: OutfitParts/Create
        public ActionResult Create()
        {
            ViewBag.AccessoryID = new SelectList(db.Accessories, "AccessoryID", "ItemName");
            ViewBag.BottomID = new SelectList(db.Bottoms, "BottomID", "ItemName");
            ViewBag.OutfitID = new SelectList(db.OutfitNames, "OutfitID", "Name");
            ViewBag.ShoeID = new SelectList(db.Shoes, "ShoeID", "ItemName");
            ViewBag.TopID = new SelectList(db.Tops, "TopID", "ItemName");
            return View();
        }

        // POST: OutfitParts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OutfitPartID,TopID,BottomID,ShoeID,AccessoryID,OutfitID")] OutfitPart outfitPart)
        {
            if (ModelState.IsValid)
            {
                db.OutfitParts.Add(outfitPart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccessoryID = new SelectList(db.Accessories, "AccessoryID", "ItemName", outfitPart.AccessoryID);
            ViewBag.BottomID = new SelectList(db.Bottoms, "BottomID", "ItemName", outfitPart.BottomID);
            ViewBag.OutfitID = new SelectList(db.OutfitNames, "OutfitID", "Name", outfitPart.OutfitID);
            ViewBag.ShoeID = new SelectList(db.Shoes, "ShoeID", "ItemName", outfitPart.ShoeID);
            ViewBag.TopID = new SelectList(db.Tops, "TopID", "ItemName", outfitPart.TopID);
            return View(outfitPart);
        }

        // GET: OutfitParts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitPart outfitPart = db.OutfitParts.Find(id);
            if (outfitPart == null)
            {
                return HttpNotFound();
            }
            ViewBag.AccessoryID = new SelectList(db.Accessories, "AccessoryID", "ItemName", outfitPart.AccessoryID);
            ViewBag.BottomID = new SelectList(db.Bottoms, "BottomID", "ItemName", outfitPart.BottomID);
            ViewBag.OutfitID = new SelectList(db.OutfitNames, "OutfitID", "Name", outfitPart.OutfitID);
            ViewBag.ShoeID = new SelectList(db.Shoes, "ShoeID", "ItemName", outfitPart.ShoeID);
            ViewBag.TopID = new SelectList(db.Tops, "TopID", "ItemName", outfitPart.TopID);
            return View(outfitPart);
        }

        // POST: OutfitParts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OutfitPartID,TopID,BottomID,ShoeID,AccessoryID,OutfitID")] OutfitPart outfitPart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outfitPart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccessoryID = new SelectList(db.Accessories, "AccessoryID", "ItemName", outfitPart.AccessoryID);
            ViewBag.BottomID = new SelectList(db.Bottoms, "BottomID", "ItemName", outfitPart.BottomID);
            ViewBag.OutfitID = new SelectList(db.OutfitNames, "OutfitID", "Name", outfitPart.OutfitID);
            ViewBag.ShoeID = new SelectList(db.Shoes, "ShoeID", "ItemName", outfitPart.ShoeID);
            ViewBag.TopID = new SelectList(db.Tops, "TopID", "ItemName", outfitPart.TopID);
            return View(outfitPart);
        }

        // GET: OutfitParts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitPart outfitPart = db.OutfitParts.Find(id);
            if (outfitPart == null)
            {
                return HttpNotFound();
            }
            return View(outfitPart);
        }

        // POST: OutfitParts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OutfitPart outfitPart = db.OutfitParts.Find(id);
            db.OutfitParts.Remove(outfitPart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeMVC/Views/OutfitNames/Create.cshtml
@model WardrobeMVC.Models.OutfitName

@{
    ViewBag.Title = "Create";
}

<h2>Your New Outfit</h2>
<h4>Lets Set some details</h4>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p>A name for your outfit</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>What season is this for?</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Season, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>What occasion?</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Who is going to be modeling it?</p>
            <div class="col-md-10">
                @Html.DropDownList("CharchterID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CharchterID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WardrobeMVC/Views/OutfitNames/Delete.cshtml
@model WardrobeMVC.Models.OutfitName

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OutfitName</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Season)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Season)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Occasion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occasion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Charachter.CharachterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Charachter.CharachterName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WardrobeMVC/Views/OutfitNames/Details.cshtml
@model WardrobeMVC.Models.FullOutfit

@{
    ViewBag.Title = "Details";
}



<h4 class="indexRowOnetext">@Url.Content(Model.Name)</h4>
<hr />
<div class="row">
    <div class="col">
        <div class="gridcontainer">
            <img class="outfitshow" src=@Url.Content(Model.Actor) />

            @foreach (var item in Model.Tops)
            {
                <img class="outfitshow" src=@Url.Content(item.Photo) />
            }
            <!---->
            @foreach (var item in Model.Bottoms)
            {
                <img class="outfitshow" src=@Url.Content(item.Photo) />
            }
            <!---->
            @foreach (var item in Model.Sheos)
            {
                <img class="outfitshow" src=@Url.Content(item.Photo) />
            }
            <!---->
            @foreach (var item in Model.Accessories)
            {
                <img class="outfitshow" src=@Url.Content(item.Photo) />
            }
        </div>
    </div>
    <div class="col outfitdetails">
        <h2>Tops in this outfit:</h2>
        @foreach (var item in Model.Tops)
        {
            <p>@Url.Content(item.ItemName)</p>
        }
        <h2>Bottoms in this outfit:</h2>
        @foreach (var item in Model.Bottoms)
        {
            <p>@Url.Content(item.ItemName)</p>
        }
        <h2>Accessories in this outfit:</h2>
        @foreach (var item in Model.Accessories)
        {
            <p>@Url.Content(item.ItemName)</p>
        }
        <h2>Shoes in this outfit:</h2>
        @foreach (var item in Model.Sheos)
        {
            <p>@Url.Content(item.ItemName)</p>
        }
        <h2>Season:</h2>
        <p>@Url.Content(Model.Season)</p>
        <h2>Occasion</h2>
        <p>@Url.Content(Model.Occasion)</p>
        <a href=@Url.Action("Create","OutfitParts")>Add Another Part</a> ||
        <a href=@Url.Action("Tutorial","Home")>Go to clothes index</a>

    </div>
</div>
<!---->
@*<dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Season)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Season)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Occasion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Occasion)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.Charachter.CharachterName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Charachter.CharachterName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.OutfitID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

WardrobeMVC/Views/OutfitNames/Edit.cshtml
@model WardrobeMVC.Models.OutfitName

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OutfitName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OutfitID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Season, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Season, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Season, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CharchterID, "CharchterID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CharchterID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CharchterID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WardrobeMVC/Views/OutfitNames/Index.cshtml
@model IEnumerable<WardrobeMVC.Models.OutfitName>

@{
    ViewBag.Title = "Index";
}

<h2>All Outfits</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>@Html.ActionLink("Create an Outfit Part","Create","OutfitParts")</p>
<p>@Html.ActionLink("Or go to the sitemap and upload some clothes","Tutorial","Home")</p>
<div class="rolodex">
    @foreach (var item in Model)
    {

        <div class="cardinfo">
            <img src=@Url.Content(item.Charachter.Photo) alt="Avatar">
            <div class="cardtextcontainer">
                <div>
                    <h4> @Html.DisplayFor(modelItem => item.Name)</h4>
                    <h4><b>Season</b> @Html.DisplayFor(modelItem => item.Season)</h4>
                    <h4><b>Occasion</b> @Html.DisplayFor(modelItem => item.Occasion)</h4>
                    <a class="cardlinks" href=@Url.Action("Details", new { id = item.OutfitID })>View</a>

                </div>
            </div>
        </div>
    }
    </div>

                @*@Html.ActionLink("Edit", "Edit", new { id = item.OutfitID }) |
                @Html.ActionLink("Details", "Details", new { id = item.OutfitID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.OutfitID })*@