WardrobeMVC/Models/Charachter.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charachter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Charachter()
        {
            this.OutfitNames = new HashSet<OutfitName>();
        }
    
        public int CharachterID { get; set; }
        public string CharachterName { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitName> OutfitNames { get; set; }
    }
}

WardrobeMVC/Controllers/CharachtersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeMVC.Models;

namespace WardrobeMVC.Controllers
{
    public class CharachtersController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: Charachters
        public ActionResult Index()
        {
            return View(db.Charachters.ToList());
        }

        // GET: Charachters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Charachter charachter = db.Charachters.Find(id);
            if (charachter == null)
            {
                return HttpNotFound();
            }
            return View(charachter);
        }

        // GET: Charachters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Charachters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CharachterID,CharachterName,Photo")] Charachter charachter)
        {
            if (ModelState.IsValid)
            {
                db.Charachters.Add(charachter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(charachter);
        }

        // GET: Charachters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Charachter charachter = db.Charachters.Find(id);
            if (charachter == null)
            {
                return HttpNotFound();
            }
            return View(charachter);
        }

        // POST: Charachters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CharachterID,CharachterName,Photo")] Charachter charachter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(charachter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(charachter);
        }

        // GET: Charachters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Charachter charachter = db.Charachters.Find(id);
            if (charachter == null)
            {
                return HttpNotFound();
            }
            return View(charachter);
        }

        // POST: Charachters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Charachter charachter = db.Charachters.Find(id);
            db.Charachters.Remove(charachter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeMVC/Controllers/OutfitNamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WardrobeMVC.Models;

namespace WardrobeMVC.Controllers
{
    public class OutfitNamesController : Controller
    {
        private WardrobeMVCEntities db = new WardrobeMVCEntities();

        // GET: OutfitNames
        public ActionResult Index()
        {
            var outfitNames = db.OutfitNames.Include(o => o.Charachter);
            return View(outfitNames.ToList());
        }

        // GET: OutfitNames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitName outfitName = db.OutfitNames.Find(id);
            FullOutfit fullOutfit = new FullOutfit();
            fullOutfit.OutfitParts = (from c in db.OutfitParts where c.OutfitID==(id) select c).ToList();
            fullOutfit.Sheos = (from c in db.OutfitParts where c.OutfitID==(id) select c.Shoe).ToList();
            fullOutfit.Tops = (from c in db.OutfitParts where c.OutfitID==(id) select c.Top).ToList();
            fullOutfit.Accessories = (from c in db.OutfitParts where c.OutfitID==(id) select c.Accessory).ToList();
            fullOutfit.Bottoms = (from c in db.OutfitParts where c.OutfitID==(id) select c.Bottom).ToList();
            fullOutfit.Name = outfitName.Name;
            fullOutfit.Occasion = outfitName.Occasion;
            fullOutfit.Season = outfitName.Season;
            fullOutfit.Actor = outfitName.Charachter.Photo;
            //foreach (OutfitPart p in fullOutfit.OutfitParts)
            //{
            //    fullOutfit.Tops.Add((from c in db.Tops where c.OutfitParts.Equals(p) select c));
            //}
            if (outfitName == null)
            {
                return HttpNotFound();
            }
            return View(fullOutfit);
        }

        // GET: OutfitNames/Create
        public ActionResult Create()
        {
            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName");
            return View();
        }

        // POST: OutfitNames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OutfitID,Name,Season,Occasion,CharchterID")] OutfitName outfitName)
        {
            if (ModelState.IsValid)
            {
                db.OutfitNames.Add(outfitName);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName", outfitName.CharchterID);
            return View(outfitName);
        }

        // GET: OutfitNames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitName outfitName = db.OutfitNames.Find(id);
            if (outfitName == null)
            {
                return HttpNotFound();
            }
            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName", outfitName.CharchterID);
            return View(outfitName);
        }

        // POST: OutfitNames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OutfitID,Name,Season,Occasion,CharchterID")] OutfitName outfitName)
        {
            if (ModelState.IsValid)
            {
                db.Entry(outfitName).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CharchterID = new SelectList(db.Charachters, "CharachterID", "CharachterName", outfitName.CharchterID);
            return View(outfitName);
        }

        // GET: OutfitNames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OutfitName outfitName = db.OutfitNames.Find(id);
            if (outfitName == null)
            {
                return HttpNotFound();
            }
            return View(outfitName);
        }

        // POST: OutfitNames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OutfitName outfitName = db.OutfitNames.Find(id);
            db.OutfitNames.Remove(outfitName);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WardrobeMVC/Views/Charachters/Create.cshtml
@model WardrobeMVC.Models.Charachter

@{
    ViewBag.Title = "Create";
}


<h4>Choose your photo</h4>
<hr />
<div class="row charachtercreaterow">
    <div class="col">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <p>  Your Name</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CharachterName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CharachterName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p>Photo Link</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }


        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>
<div class="col">
    <h2>Upload your photo to an image hosting site and paste the link here. We reccomend a 360 x 922 pixel size for optimal results.</h2>

</div>
</div>

WardrobeMVC/Views/Charachters/Delete.cshtml
@model WardrobeMVC.Models.Charachter

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Charachter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharachterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharachterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WardrobeMVC/Views/Charachters/Details.cshtml
@model WardrobeMVC.Models.Charachter

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Charachter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharachterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharachterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CharachterID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WardrobeMVC/Views/Charachters/Edit.cshtml
@model WardrobeMVC.Models.Charachter

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Charachter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CharachterID)

        <div class="form-group">
            @Html.LabelFor(model => model.CharachterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharachterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharachterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WardrobeMVC/Views/Charachters/Index.cshtml
@model IEnumerable<WardrobeMVC.Models.Charachter>

@{
                /**/

                ViewBag.Title = "Index";
}

<h1>Availible Models</h1>

<a href=@Url.Action("Charachters","Create")> Not what you were looking for? Upload your picture! </a>
<hr />
<div class="rolodex">
    @foreach (var item in Model)
    {

        <div class="cardinfo">
            <img src=@Url.Content(item.Photo) alt="Avatar">
            <div class="cardtextcontainer">
                <div>
                    <h4><b> @Html.DisplayFor(modelItem => item.CharachterName)</b></h4>
                   <a class="cardlinks" href= @Url.Action( "Edit", new { id = item.CharachterID }) >Edit</a> 
                   <a class="cardlinks" href=@Url.Action( "Details", new { id = item.CharachterID }) >Details</a>
                 <a class="cardlinks"href=   @Url.Action( "Delete", new { id = item.CharachterID }) >Delete</a>
                </div>
            </div>
        </div>
    }

</div>

<h1 style="margin-top:100px">Ready To make your outfit?</h1>
<a href=@Url.Action("Create","OutfitNames") >Lets Go!</a>